export const AUTH_POSTGRES_SEQUELIZE = 'AUTH_POSTGRES_SEQUELIZE';
export const AUTH_USER_MODEL = 'AUTH_USER_MODEL';
export const AUTH_REQUEST_LOG_MODEL = 'AUTH_REQUEST_LOG_MODEL';
export const ARTSAKH_CONNECTION = 'ARTSAKH_CONNECTION';
