version: '3.8'

services:
   app:
      build: .
      container_name: nest_app
      ports:
         - '8000:8000'
      env_file: .env
      depends_on:
         - mysql_db1
         - mysql_db2
      restart: unless-stopped

   mysql_db1:
      image: mysql:8.0
      container_name: mysql_db1
      environment:
         MYSQL_ROOT_PASSWORD: ${DATABASE_USER_PASSWORD_ASYLUM}
         MYSQL_DATABASE: ${DATABASE_NAME_ASYLUM}
         MYSQL_USER: ${DATABASE_USERNAME_ASYLUM}
         MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD_ASYLUM}
      ports:
         - '3307:3306'
      volumes:
         - mysql_data1:/var/lib/mysql
      restart: unless-stopped

   mysql_db2:
      image: mysql:8.0
      container_name: mysql_db2
      environment:
         MYSQL_ROOT_PASSWORD: ${DATABASE_USER_PASSWORD_WP}
         MYSQL_DATABASE: ${DATABASE_NAME_WP}
         MYSQL_USER: ${DATABASE_USERNAME_WP}
         MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD_WP}
      ports:
         - '3308:3306'
      volumes:
         - mysql_data2:/var/lib/mysql
      restart: unless-stopped

volumes:
   mysql_data1:
   mysql_data2:
