export * from './IWp.model';
export * from './IEatm.model';
export * from './IWorkerCard.model';
export * from './IEatmFamily.model';
export * from './IWorkerFine.model';
export * from './IWorkerAdvanced.model';
export * from './ITableResultsMap.model';
export * from './IGetFullDataByPnumResponse.model';
export * from './IGetWpFamilyMemberResponse.model';
