export const RBAC_SEQUELIZE = 'RBAC_SEQUELIZE';
export const API_CLIENT_MODEL = 'API_CLIENT_MODEL';
export const PERMISSION_MODEL = 'PERMISSION_MODEL';
export const API_CLIENT_PERMISSION_MODEL = 'API_CLIENT_PERMISSION_MODEL';
