export interface IRefugeeDetail {
   personal_id: number;
   case_id: number;
   f_name_arm: string;
   f_name_eng: string;
   l_name_arm: string;
   l_name_eng: string;
   m_name_arm: string | null;
   m_name_eng: string | null;
   b_day: string | null;
   b_month: string | null;
   b_year: string | null;
   sex: number;
   citizenship: number | null;
   previous_residence: number | null;
   citizen_adr: string | null;
   residence_adr: string | null;
   departure_from_citizen: string | null;
   departure_from_residence: string | null;
   arrival_date: string | null;
   doc_num: string | null;
   etnicity: number | null;
   religion: number | null;
   invalid: number;
   pregnant: number;
   seriously_ill: number;
   trafficking_victim: number;
   violence_victim: number;
   comment: string | null;
   illegal_border: number;
   transfer_moj: number;
   deport_prescurator: number;
   prison: number;
   role: number;
   image: string;
   person_status: number;
   CITIZENSHIP_COUNTRY_NAME: string | null;
   PREVIOUS_RESIDENCE_COUNTRY_NAME: string | null;
   ETNICITY_NAME: string | null;
   RELIGION_NAME: string | null;
   ROLE_NAME: string | null;
   PERSON_STATUS_NAME: string | null;
   contact_email: string | null;
   contact_tel: string | null;
   STREET_NAME: string | null;
   BUILDING_NUMBER: string | null;
   APPARTMENT_NUMBER: string | null;
   MARZ_NAME: string | null;
   COMMUNITY_NAME: string | null;
   SETTLEMENT_NAME: string | null;
}
